name: tartv_app
description: "TarTV - Aplicativo IPTV completo com suporte a Xtream Codes, M3U e player nativo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Interface básica
  cupertino_icons: ^1.0.6
  
  # Requisições HTTP
  http: ^1.1.0
  
  # Gerenciamento de estado
  provider: ^6.1.2
  
  # Player de vídeo
  video_player: ^2.8.6
  chewie: ^1.8.0
  
  # Armazenamento local
  shared_preferences: ^2.2.2
  
  # Cache de imagens
  cached_network_image: ^3.3.1
  
  # File picker para M3U (compatível com Android)
  file_picker: ^8.0.3
  
  # Path provider para arquivos
  path_provider: ^2.1.2
  
  # Wake lock para player
  wakelock_plus: ^1.2.5
  
  # Package info
  package_info_plus: ^8.0.0
  
  # Permissions para Android
  permission_handler: ^11.3.1
  
  # URL launcher para links externos
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Configuração de ícones
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "tartv-icon-source.png"
  remove_alpha_ios: true
